version: '3.3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5434:5432"  # Expose PostgreSQL's 5432 port to the host's 5433 port
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=golearn
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - golearn-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64  # Ensure the platform is ARM64 for Mac M2
    container_name: go_startup
    depends_on:
      - postgres
    ports:
      - "8081:8081"  # Expose the container's 8080 port to the host's 8081 port
    environment:
      - PORT=8081
      - REDIRECTION_URL=http://localhost:8081
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=golearn
      - DB_SSL_MODE=disable
    volumes:
      - .:/app/src  # Bind the current directory to /app/src in the container
    networks:
      - golearn-network
    restart: unless-stopped
    command: ["/app/main"]

volumes:
  postgres-data:

networks:
  golearn-network:
    driver: bridge